name: gesundheit
description: Base package for all healthcare applications.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  creator: ^0.2.1
  csv: ^5.0.1
  cupertino_icons: ^1.0.5
  fhir: ^0.9.0
  fhir_at_rest: ^0.9.0
  fhir_auth: ^0.9.0-1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_login: ^4.0.0
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  go_router: ^5.0.2
  graphic: ^0.10.7
  hidden_drawer_menu: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  mdi: ^5.0.0-nullsafety.0
  package_info_plus: ^1.4.3+1
  shared_preferences: ^2.0.15
  table_calendar: ^3.0.7

dev_dependencies:
  analyzer: ^5.1.0
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.1.1
  go_router_builder: ^1.0.14
  json_serializable: ^6.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/growth_tables/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
