name: gesundheit
description: Base package for all healthcare applications.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  creator: ^0.2.0
  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  package_info_plus: ^1.4.3+1
  shared_preferences: ^2.0.15

dev_dependencies:
  analyzer: ^4.2.0
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
